### ISSUE TITLE
Minification Error

### ISSUE THREAD

**Issue by treyseals** [bdkjones/CodeKit#645]
Rare issue I've never encountered when saving a compiled js file:

_Minification failed with this error: ERROR: Cannot read property 'comments_before' of undefined_

_at AST_Return._do_print (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:8135:47)
    at /Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:8147:14
    at doit (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:7570:13)
    at AST_Return.<anonymous> (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:7577:13)
    at AST_Return.AST_Node.print (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:10108:18)
    at /Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:7881:22
    at Array.forEach (<anonymous>)
    at display_body (/Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:7872:14)
    at /Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:7928:17
    at /Applications/CodeKit.app/Contents/Resources/engines/node_modules/terser/dist/bundle.min.js:7271:19_

**Comment by treyseals** [comment]
Restarting CodeKit fixed the issue....should've tried this first...idiot, Jeff.
